name: fuzzy_track
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.3.1
  fast_immutable_collections: ^7.4.1
  freezed_annotation: ^2.1.0
  fuzzylogic:
    git:
      url: https://github.com/crosstyan/fuzzylogic.git
      ref: bump
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  lints: ^2.0.0
  test: ^1.16.0
