name: fuzzy_track
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
 fuzzylogic:
   git:
     url: https://github.com/crosstyan/fuzzylogic.git
     ref: bump

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
